const student = [
    {
      id: 1,
      first_name: "Fred",
      last_name: "Gandrich",
      email: "fgandrich0@china.com.cn",
      gender: "Male",
      ip_address: "240.206.59.225",
    },
    {
      id: 2,
      first_name: "Osborn",
      last_name: "Vitall",
      email: "ovitall1@thetimes.co.uk",
      gender: "Genderfluid",
      ip_address: "28.190.69.154",
    },
    {
      id: 3,
      first_name: "Gussie",
      last_name: "Youd",
      email: "gyoud2@devhub.com",
      gender: "Female",
      ip_address: "18.161.91.25",
    },
    {
      id: 4,
      first_name: "Cassie",
      last_name: "Hynson",
      email: "chynson3@ning.com",
      gender: "Male",
      ip_address: "113.43.113.163",
    },
    {
      id: 5,
      first_name: "Andria",
      last_name: "Astle",
      email: "aastle4@eepurl.com",
      gender: "Female",
      ip_address: "36.5.10.105",
    },
    {
      id: 6,
      first_name: "Nicola",
      last_name: "Hopfer",
      email: "nhopfer5@tuttocitta.it",
      gender: "Bigender",
      ip_address: "61.142.196.45",
    },
    {
      id: 7,
      first_name: "Leoine",
      last_name: "Denisyuk",
      email: "ldenisyuk6@ibm.com",
      gender: "Female",
      ip_address: "137.179.113.117",
    },
    {
      id: 8,
      first_name: "Liana",
      last_name: "Banstead",
      email: "lbanstead7@wikia.com",
      gender: "Female",
      ip_address: "217.169.189.35",
    },
    {
      id: 9,
      first_name: "Mathias",
      last_name: "Gergolet",
      email: "mgergolet8@sciencedaily.com",
      gender: "Male",
      ip_address: "4.142.203.107",
    },
    {
      id: 10,
      first_name: "Zonnya",
      last_name: "Izzatt",
      email: "zizzatt9@moonfruit.com",
      gender: "Female",
      ip_address: "153.60.243.24",
    },
  ];
  
  module.exports = student;
  